server:
  port: 8080

spring:
  application:
    name: scheduler-core
  datasource:
    url: jdbc:h2:mem:schedulerdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

# executor:
#   service:
#     url: http://localhost:8081

async:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 25