server:
  port: 8082

spring:
  application:
    name: scheduler-monitor
  datasource:
    url: jdbc:h2:mem:monitordb
    username: sa
    password: password

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}